### ISSUE TITLE
Add illustrations/images

### ISSUE THREAD

**Issue by sverhoeven** [NLESC-JCER/cpp2wasm#32]
As a reader of the guide I find it very text and code heavy. It would help if it had some illustrations or images that would break up the text. 

One of the images or a collage could be used in the entangled examples (see https://github.com/entangled/examples/issues/1)

**Comment by sverhoeven** [comment]
`entangled lint dumpToGraphViz | neato  -Tpng -o refs.png` can generate a graph of all the anchors.

![refs](https://user-images.githubusercontent.com/1713488/83767104-7c9ce000-a67d-11ea-9e6f-68e39ef38d37.png)

**Comment by jspaaks** [comment]
Hi @cwmeijer I had forgotten that you had assigned yourself on this issue and created PR #65 which adds images to some of the major sections in the README. Hopefully this does not interfere with any work you may have done already. Otherwise, feel free to cancel the PR, as you went through the official channels and I did not.

**Comment by sverhoeven** [comment]
Solved partially by #65 and https://github.com/NLESC-JCER/cpp2wasm/issues/36 
So good enough for now.
